### ISSUE TITLE
Lega commander file listing NPE

### ISSUE THREAD

**Issue by joshbaskaran** [elixir-oslo/lega-commander#11]
When listing files in a folder previously not created, the program crashes with a NPE. This case should be handled without crashing.

There are three major user scenarios where this is happening:

- [x] A new user does an upload for the very first time, and thus the inbox of the user has never been created before (the code list the current files in an inbox to avoid accidental overwriting of previous uploaded file with exact same name). 
- [x] A new user run "inbox -l"
- [x] A user runs "outbox -l" when there has not been any data staged in the outbox yet, and hence it's not created. (different error form "inbox -l"

**Comment by kjellp** [comment]
Point 1. implemented and tested in [PR#10](https://github.com/elixir-oslo/lega-commander/pull/10)

**Comment by pavelvazquez** [comment]
I believe the issues with the error handling is resolved. Ready for review and merge (or rebase?) with master. 

Note that the solution relies on checking specific error messages in the response body, which might impact functionality if these messages change in the future.
