### ISSUE TITLE
Test install script on Windows

### ISSUE THREAD

**Issue by joshbaskaran** [elixir-oslo/lega-commander#14]
Recent changes to goreleaser broke the install sciprt. The fix has been implemented and tested on MacOS and Linux environments but needs testing on Windows.

**Comment by pavelvazquez** [comment]
I attempted to test this on an NREC Windows VM, but realised the provided binaries are specific to ARM architectures.
Which seems to be more typical for devices like smartphones, tablets, etc. Unfortunately, I couldn't test for PC.

My suggestion would be to extend the go-releaser to support PC architectures (x86 and x64?)? 

I see that these architectures are supported in previous versions.

**Comment by joshbaskaran** [comment]
Could you pass on the exact error it produces? I think it has to do with how the install script handles Windows environments.

**Comment by pavelvazquez** [comment]
It is very generic. "This version of lega-commander.exe is not compatible with the version of Windows you're running. Check your computer's system information and contact the software publisher"

**Comment by joshbaskaran** [comment]
Windows x86_64 binaries are already part of the release. Looking at where this message originates from, it's again an issue of how naming conventions but this time on windows. Fixable, just needs some finessing.

**Comment by pavelvazquez** [comment]
I have successfully tested Windows x86_64
